### ISSUE TITLE
关于 submodule 和 github action

### ISSUE THREAD

**Issue by yi-Xu-0100** [Kr328/V2rayDomains2Clash#2]
我看到是定时更新，但是没看到 action 的 workflow 文件，是其他方式对本仓库操作的吗？

准确的说，actions 中的 workflow 指向的文件我没找到，包含在 submodule 里面？submodule 的内容被修改了吗？还是只是最新版本的那个仓库？我看到的 github 修改记录中是 submodule 部分被修改，是指更新到最新版本吗？

如果是 github action ，是否可以直接用 actions/checkout 将这个引入的仓库加载？

**Comment by Kr328** [comment]
更新是在我自己的服务器上更新的 也就是那个 mirror

workflow 不是很用的来

**Comment by yi-Xu-0100** [comment]
哦哦，这个 submodule 有修改吗？只是跟随更新是吗？

**Comment by Kr328** [comment]
只是跟随上游 应该能够直接点开的吧

**Comment by yi-Xu-0100** [comment]
可以的，谢谢~😀 感觉很棒

**Comment by yi-Xu-0100** [comment]
我试着写了个 workflow 来生成，个人测试无误，希望有所帮助。😁 （#3）
