### ISSUE TITLE
url 错误

### ISSUE THREAD

**Issue by yi-Xu-0100** [Kr328/V2rayDomains2Clash#4]
![image](https://user-images.githubusercontent.com/25523606/104812527-d386ac80-583d-11eb-9e5e-d5f208c87fec.png)

发现这里的 url 错误了，是 v2fly 。readme 中的是对的。

~还有就是，现在是 github action 生成方式的话，需不需要提交 request 将 submodule 部分（那个文件夹和 .submodule ）删除掉？~

想起来，保留 submodule ，可以方便 `git clone --recurse-submodules` 项目后直接运行。

**Comment by Kr328** [comment]
fixed
